services:
  postgres:
    image: postgres:16
    container_name: postgres_db2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
